//
// Created by Flavia Rivero on 2/11/24.
//

#include "excepcion.h"
#include <stdexcept>

void lanzaExcepcion5() {
    throw std::runtime_error("Error en la funci√≥n lanzaExcepcion");
}

